import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Role } from '../auth/roles.enum';

/**
 * User entity — persisted in the `users` table.
 *
 * Columns:
 *  - id:        UUID primary key, generated by the database.
 *  - email:     unique email address (used as login identifier).
 *  - password:  bcrypt hash of the user's password — never plain text.
 *  - role:      single Role value; defaults to PLAYER on registration.
 *  - createdAt: timestamp set automatically on insert.
 */
@Entity('users')
export class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'varchar', unique: true })
  email!: string;

  @Column({ type: 'varchar' })
  password!: string;

  @Column({ type: 'varchar', default: Role.PLAYER })
  role!: Role;

  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;
}
